CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating DECIMAL
(1, 0),
    date_published TIMESTAMPTZ DEFAULT now
() NOT NULL
)